# Generated by Django 5.0.6 on 2024-06-25 23:47

import npi_field.modelfields
import npi_field.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestNPIModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "npi",
                    npi_field.modelfields.NPIField(
                        blank=True,
                        null=True,
                        validators=[npi_field.validators.npi_validator],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TestPKModel",
            fields=[
                (
                    "npi",
                    npi_field.modelfields.NPIField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[npi_field.validators.npi_validator],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
